language: php

php:
    - 7.1
    - 7.2

cache:
    directories:
        - ~/.composer/cache/files

before_install:
    - phpenv config-rm xdebug.ini || true

install:
    - composer update --prefer-dist

script:
    - composer validate --strict

    - vendor/bin/behat --strict
